/**
 * Tutorial video registry.
 *
 * Each entry describes one short (≤4 min) screen-recorded walkthrough,
 * surfaced contextually via <TutorialVideo /> exactly where the workflow
 * it explains lives. The media files are generated by the automated
 * recorder in `scripts/record-tutorials/` and served from `/tutorials/`;
 * until a file exists the component degrades to the written summary.
 *
 * The wording of the subtitles is NOT here — it lives in
 * `docs/tutorials/<key>.md` (the shot lists), which the recorder reads.
 */

export type TutorialKey =
  | "first-15-minutes"
  | "petty-cash-vs-expenses"
  | "invoice-income-link"
  | "proof-of-payment"
  | "bulk-import"
  | "cases-and-approvals"
  | "tenant-checkout"
  | "utilities-metering"
  | "service-charge"
  | "rent-increases"
  | "whatsapp-reminders";

export type TutorialVideo = {
  key: TutorialKey;
  title: string;
  durationSec: number;          // target; updated to actual after recording
  videoUrl: string | null;      // null = not yet recorded
  posterUrl: string | null;
  subtitleUrl: string | null;   // WebVTT
  summary: string;              // 3–6 sentence written version, must stand alone
  steps: string[];              // ordered list shown beneath the player
  next?: TutorialKey;           // the logical next tutorial
  relatedDocs?: { label: string; href: string }[];
};

export const TUTORIAL_VIDEOS: Record<TutorialKey, TutorialVideo> = {
  "first-15-minutes": {
    key: "first-15-minutes",
    title: "Your first 15 minutes",
    durationSec: 136,
    videoUrl: "/tutorials/first-15-minutes.mp4",
    posterUrl: "/tutorials/first-15-minutes.jpg",
    subtitleUrl: "/tutorials/first-15-minutes.vtt",
    summary:
      "A fresh organisation starts empty, and the Setup Checklist on the dashboard is the fastest path out of that. This walkthrough adds a property with its units, puts a tenant on a lease, and records the first income and expense entries so the dashboard, reports and arrears views have real numbers to work with. Along the way it shows where the tenant portal link comes from and why the checklist percentage is worth driving to 100. Every later tutorial assumes this base state exists.",
    steps: [
      "Create your property and its units (the onboarding wizard or Properties → Add property).",
      "Open the dashboard — the Setup Checklist shows what is configured and what is missing, with a link for each gap.",
      "Add a tenant on the Tenants page: unit, monthly rent, lease dates.",
      "Generate the tenant's portal link from the tenant detail page and share it — no login needed on their side.",
      "Record one income entry (Income → Add) and one expense (Expenses → Add) so the money pages come alive.",
      "Watch the checklist climb — each completed row is one less thing the app has to nag you about.",
    ],
    next: "bulk-import",
    relatedDocs: [{ label: "Help & Guide", href: "/guide.html" }],
  },

  "petty-cash-vs-expenses": {
    key: "petty-cash-vs-expenses",
    title: "Petty cash vs expenses",
    durationSec: 112,
    videoUrl: "/tutorials/petty-cash-vs-expenses.mp4",
    posterUrl: "/tutorials/petty-cash-vs-expenses.jpg",
    subtitleUrl: "/tutorials/petty-cash-vs-expenses.vtt",
    summary:
      "Spending recorded directly as a petty-cash OUT never reaches your profit-and-loss — only the Expenses page feeds the P&L. The correct habit is one entry on the Expenses page with \"Paid from petty cash\" ticked, which auto-creates the linked petty-cash OUT for you. This walkthrough deliberately does it the wrong way first, so you can see the nudge and the \"unaccounted cash out\" banner the app raises, then fixes the entry with Record as expense instead. It ends with the one-click convert that repairs old unlinked rows without double-counting.",
    steps: [
      "Record spending on the Expenses page and tick \"Paid from petty cash\" — the OUT row is created and linked automatically.",
      "If you enter an OUT directly on the Petty Cash page, a nudge offers \"Record as expense instead\" — take it.",
      "The \"unaccounted cash out\" banner totals every unlinked OUT; use \"show only these\" to list them.",
      "Fix an old unlinked row with \"Convert to expense\" — it creates a fully-paid cash expense and links it, without minting a second OUT.",
      "Petty cash IN entries (top-ups) stay on the Petty Cash page — they are float movements, not spending.",
    ],
    next: "cases-and-approvals",
    relatedDocs: [{ label: "Help & Guide", href: "/guide.html" }],
  },

  "invoice-income-link": {
    key: "invoice-income-link",
    title: "How invoices and income stay in sync",
    durationSec: 131,
    videoUrl: "/tutorials/invoice-income-link.mp4",
    posterUrl: "/tutorials/invoice-income-link.jpg",
    subtitleUrl: "/tutorials/invoice-income-link.vtt",
    summary:
      "Invoices are billing artifacts; the money itself lives in income entries — and the app keeps the two linked so you never book the same rent twice. Marking an invoice paid creates the matching income entry automatically, and recording a rent income entry finds the open invoice for that tenant and month and marks it paid. This walkthrough shows both directions, the bulk mark-paid and bulk-send actions for month-end, and the safe way to reverse a mistake: \"Revert to unpaid\", which removes the linked income entry in the same step so your books stay clean.",
    steps: [
      "Mark an invoice paid (row status dropdown, or bulk-select → Mark paid) — an income entry is created for you.",
      "Or record the payment on the Income page — the open invoice for that tenant and month flips to PAID by itself.",
      "Never enter both; the link exists so one action does both sides.",
      "Month-end: select many invoices and use Send (emails each PDF) or Mark paid in bulk.",
      "Made a mistake? Use \"Revert to unpaid…\" on a paid invoice — it deletes the linked income entry too, so nothing double-counts.",
    ],
    next: "proof-of-payment",
    relatedDocs: [{ label: "Help & Guide", href: "/guide.html" }],
  },

  "proof-of-payment": {
    key: "proof-of-payment",
    title: "Verifying tenant proof of payment",
    durationSec: 111,
    videoUrl: "/tutorials/proof-of-payment.mp4",
    posterUrl: "/tutorials/proof-of-payment.jpg",
    subtitleUrl: "/tutorials/proof-of-payment.vtt",
    summary:
      "Tenants can submit proof of payment — a screenshot, a PDF, or just the M-Pesa confirmation text — from their portal link, with no login. The invoice then shows an amber \"Check Proof\" badge and waits in PENDING_VERIFICATION; nothing touches your books until you decide. Clicking the badge opens a drawer with the proof previewed inline, where you confirm the amount and payment method and approve (marking it paid, creating the income entry, and filing the proof in the tenant's document vault) or reject it, which returns the invoice to its previous state.",
    steps: [
      "The tenant opens their portal link → Balance tab → \"I've paid this\" and attaches a file or pastes the confirmation text.",
      "The invoice now shows an amber \"Check Proof\" badge on the tenant's Invoices tab.",
      "Click the badge — the drawer previews the file or text without downloading anything.",
      "Check the amount and payment method fields, then Approve: invoice becomes PAID, the income entries are created, the proof is vaulted, and the tenant is emailed a receipt.",
      "Not right? Reject — the file is discarded and the invoice returns to SENT or OVERDUE for follow-up.",
    ],
    next: "petty-cash-vs-expenses",
    relatedDocs: [{ label: "Help & Guide", href: "/guide.html" }],
  },

  "bulk-import": {
    key: "bulk-import",
    title: "Bulk import without duplicates",
    durationSec: 123,
    videoUrl: "/tutorials/bulk-import.mp4",
    posterUrl: "/tutorials/bulk-import.jpg",
    subtitleUrl: "/tutorials/bulk-import.vtt",
    summary:
      "The Import page moves you off spreadsheets in minutes: download a template, fill it, upload it, and the rows are validated in your browser before anything is sent. Every importer skips rows it has seen before, so re-uploading the same file is safe. The \"Update existing records\" toggle turns a re-upload into a refresh — matched rows are updated instead of skipped — and for expenses there is a full round-trip: \"Export existing\" downloads your current data with an ID column, so you can edit any field in Excel and re-upload without creating duplicates.",
    steps: [
      "Pick the tab for what you're importing (tenants, income, expenses, units…) and download its template.",
      "Fill the Data sheet — the second row marks which columns are REQUIRED; the Instructions sheet explains each one.",
      "Upload the file — rows are validated client-side and errors are listed per row before any import happens.",
      "Re-uploading is safe: duplicate rows are skipped, not doubled.",
      "To correct existing data, tick \"Update existing records\"; for expenses, use \"Export existing\" first so the ID column makes every edit land on the right row.",
    ],
    next: "invoice-income-link",
    relatedDocs: [{ label: "Help & Guide", href: "/guide.html" }],
  },

  "cases-and-approvals": {
    key: "cases-and-approvals",
    title: "Cases, stages and owner approvals",
    durationSec: 209,
    videoUrl: "/tutorials/cases-and-approvals.mp4",
    posterUrl: "/tutorials/cases-and-approvals.jpg",
    subtitleUrl: "/tutorials/cases-and-approvals.vtt",
    summary:
      "Every maintenance job automatically gets a case: one workspace holding the timeline, comments, attachments and stage of that issue, so nothing lives in WhatsApp threads. Cases move through a fixed forward-only workflow — advance the stage as work progresses, and the case records who was waiting on whom and for how long. When you need the owner's sign-off on a repair, request an approval from the case: the owner gets a magic-link email, approves or rejects on their phone with no login, and the decision lands back on the timeline and advances the stage automatically.",
    steps: [
      "Report a maintenance job — a case is created for it automatically (see the \"Open case →\" link on the job card).",
      "Work the case: comments, attachments and emails all land on one timeline.",
      "Use Advance to move the stage forward as work progresses; regressing requires a reason.",
      "Need sign-off? \"Request approval\" emails the owner a magic link — they approve or reject without logging in.",
      "The decision is recorded on the timeline, the case advances by itself, and the SLA clock stops waiting on the owner.",
    ],
    next: "tenant-checkout",
    relatedDocs: [{ label: "Help & Guide", href: "/guide.html" }],
  },

  "tenant-checkout": {
    key: "tenant-checkout",
    title: "Tenant checkout and deposit settlement",
    durationSec: 159,
    videoUrl: "/tutorials/tenant-checkout.mp4",
    posterUrl: "/tutorials/tenant-checkout.jpg",
    subtitleUrl: "/tutorials/tenant-checkout.vtt",
    summary:
      "Checkout replaces the paper move-out form with one page that settles everything at once: unit condition, outstanding rent, itemised deposit deductions, keys, utility transfers and how the refund goes out. The sticky settlement box recalculates the refund live as you add deductions, so the tenant can see exactly how the number was reached. Finalising is atomic — the tenant is marked vacated, the unit becomes vacant, any damage cost you keep becomes a reinstatement expense, and a signature-ready PDF is generated for both parties to sign.",
    steps: [
      "Open the tenant's detail page and click Checkout in the header.",
      "Work through the sections: condition, rent balance (outstanding invoices are pre-computed), deductions, keys, utilities, refund method.",
      "Add itemised deductions — the sticky settlement box updates the refund live.",
      "Save as you go; the checkout stays IN_PROGRESS until you finalise.",
      "Finalise: tenant vacated, unit set to VACANT, damage kept by the landlord becomes a reinstatement expense, and the deposit settlement is recorded.",
      "Download the PDF for signatures — the page becomes read-only from here.",
    ],
    relatedDocs: [{ label: "Help & Guide", href: "/guide.html" }],
  },

  "utilities-metering": {
    key: "utilities-metering",
    title: "Water and electricity meters",
    durationSec: 179,
    videoUrl: "/tutorials/utilities-metering.mp4",
    posterUrl: "/tutorials/utilities-metering.jpg",
    subtitleUrl: "/tutorials/utilities-metering.vtt",
    summary:
      "At month end every water and electricity meter is read — by the caretaker on a phone with a photo of each dial, or by a manager typing into the Readings table, where Enter jumps to the next meter. Readings on paper or in a spreadsheet can be imported: download the month's sheet, fill in the Current reading column, and import it; every row is previewed before anything is saved. With no signal, readings wait on the phone until it reconnects. A manager then approves the readings on Review & bill (unusual jumps are flagged) and bills them onto the next rent invoice. Paid & unpaid is the chase list of who owes water and electricity, and Reconciliation shows the council, KPLC and generator costs against what tenants paid, with the surplus going to the owner. When a tenant moves out, the checkout takes a final reading per meter and the last bill comes off the deposit.",
    steps: [
      "Utilities → Readings, pick the month: type each meter's current reading (Enter moves down), or group By unit to follow the walk.",
      "Or Download sheet, fill in Current reading, and Import readings — check the preview, then import.",
      "Review & bill (previous month): check flagged readings, Select all, Approve.",
      "Bill onto the next invoice — readings join the rent invoice, or a separate utilities invoice if that one is already paid.",
      "Paid & unpaid: see who owes water and electricity; tick them and email reminders, or export Excel / PDF.",
      "Reconciliation: council water vs collections (borehole surplus to the owner); KPLC bulk meter vs units billed, vacant units and common areas.",
      "Move-out: the tenant's Checkout takes a final reading per meter — the final bill goes on one invoice paid from the deposit.",
    ],
    relatedDocs: [{ label: "Help & Guide — Water & Electricity", href: "/guide.html#utilities" }],
  },

  "service-charge": {
    key: "service-charge",
    title: "Service charge budgets",
    durationSec: 94,
    videoUrl: "/tutorials/service-charge.mp4",
    posterUrl: "/tutorials/service-charge.jpg",
    subtitleUrl: "/tutorials/service-charge.vtt",
    summary:
      "An apartment block's service charge is set one year at a time. Start the new year's budget from last year's — the costs and the month the year starts carry over — then add what is new and save. The total is split between units by floor area, and each unit's suggested monthly charge sits next to what its tenant pays today; Apply to tenants brings everyone into line from their next invoice. Budget vs actual tracks what has been spent against the budget, cost by cost. When a year ends, the year-end statement sets each tenant's share of what was actually spent against what they were billed: shortfalls become draft balancing invoices in one click, credits are listed to refund, and days a unit stood empty are the owner's share. Publish the statement and each tenant downloads theirs from the portal.",
    steps: [
      "Finances → Service Charge, pick the block and the year: Start from last year's budget (or a blank one).",
      "Budget: one line per shared cost for the year — add, change or remove lines, then Save budget.",
      "Check each unit's share and suggested monthly charge; Apply to tenants to bill it from the next invoices.",
      "Budget vs actual: spending so far against the budget to date, cost by cost.",
      "After the year ends, Year-end statement: each tenant's share against what they were billed; the vacant days fall to the owner.",
      "Tick the tenants and Raise balancing invoices (drafts — send them from Invoices); refund or offset the credits.",
      "Publish to portal (or Email statements) so each tenant has their own statement.",
    ],
    relatedDocs: [{ label: "Help & Guide — Service Charge Budgets", href: "/guide.html#service-charge" }],
  },

  "rent-increases": {
    key: "rent-increases",
    title: "Rent increases",
    durationSec: 76,
    videoUrl: "/tutorials/rent-increases.mp4",
    posterUrl: "/tutorials/rent-increases.jpg",
    subtitleUrl: "/tutorials/rent-increases.vtt",
    summary:
      "A lease's rent review terms — a percentage or a fixed amount, how often, the first review and the notice period — are recorded on the tenant. A month before the notice deadline, the Inbox shows Rent increase due with today's rent, the new one and the date the notice must go out. Review increase opens the tenant's rent review: the new rent is worked out from the lease and can be adjusted, and the effective date is the review date — or, if the deadline has passed, the first month that still gives full notice, never backdated. Scheduling it means invoices from that month bill the new rent and the tenant's rent switches by itself on the day. The notice letter can be downloaded or emailed with the PDF attached, and a review with no rise is recorded so the next reminder is for the following year.",
    steps: [
      "Record the lease's terms on the tenant: Edit → Rent Increase (percentage or fixed amount), Every (years), First Review, Notice (days).",
      "When the Inbox shows Rent increase due, click Review increase.",
      "On the Rent History tab, check the proposed rent and the effective date — adjust either if needed.",
      "Schedule increase: invoices from that month bill the new rent; the tenant's rent switches on the day.",
      "Send the notice: download the letter, or Email notice (PDF attached, logged on the Comms tab).",
      "No rise this time? Click No increase this time — the next reminder is for the following review.",
    ],
    relatedDocs: [{ label: "Help & Guide — Rent increases", href: "/guide.html#rent-increases" }],
  },

  "whatsapp-reminders": {
    key: "whatsapp-reminders",
    title: "WhatsApp reminders",
    durationSec: 70,
    videoUrl: "/tutorials/whatsapp-reminders.mp4",
    posterUrl: "/tutorials/whatsapp-reminders.jpg",
    subtitleUrl: "/tutorials/whatsapp-reminders.vtt",
    summary:
      "Tenants who never read email can get their reminders on WhatsApp, sent from the manager's own WhatsApp — nothing to set up and no cost. Every overdue invoice in the Inbox has a WhatsApp action: the reminder is written for you with the amount outstanding, the days overdue and a link to the tenant's portal, and sending opens WhatsApp with the chat and message ready for you to press send. Select several overdue tenants and Remind on WhatsApp takes you through them one chat at a time; a tenant without a portal link can get one as you send, never without you asking. Each message is logged on the tenant's Comms tab as a send attempt, since WhatsApp can't confirm delivery. Tenants need a phone number with its country code — without one the button stays grey.",
    steps: [
      "Save each tenant's phone with the country code (e.g. +254 712 345 678) — a number starting with 0 is read as the property's country.",
      "Inbox: on an overdue invoice, click WhatsApp, check the reminder and Send via WhatsApp.",
      "WhatsApp opens with the chat and message ready — press send there.",
      "Several tenants? Tick their overdue invoices and click Remind on WhatsApp; tap through them one chat at a time.",
      "No portal link yet? Create portal link & send — or Send without the link.",
      "The tenant page's WhatsApp button and Draft Email's Send via WhatsApp offer the receipt, renewal and expiry messages too.",
      "Every send is on the tenant's Comms tab as a send attempt.",
    ],
    relatedDocs: [{ label: "Help & Guide — WhatsApp reminders", href: "/guide.html#whatsapp" }],
  },
};

export const TUTORIAL_ORDER: TutorialKey[] = [
  "first-15-minutes",
  "bulk-import",
  "invoice-income-link",
  "proof-of-payment",
  "petty-cash-vs-expenses",
  "cases-and-approvals",
  "tenant-checkout",
  "utilities-metering",
  "service-charge",
  "rent-increases",
  "whatsapp-reminders",
];
