-- Enable Row Level Security on all public tables
-- All data access goes through Prisma (postgres role) which bypasses RLS.
-- This blocks direct PostgREST/anon API access to every table.

ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserOrganizationMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Property" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PropertyAccess" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ManagementFeeConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ManagementAgreement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Unit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tenant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TenantDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RentHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IncomeEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OwnerInvoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExpenseEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExpenseLineItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExpenseUnitAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExpenseDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecurringExpense" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PettyCash" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ArrearsCase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ArrearsEscalation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DepositSettlement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MaintenanceJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Asset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetMaintenanceSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AssetMaintenanceLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InsurancePolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InsurancePolicyDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BuildingConditionReport" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AirbnbGuest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BookingGuest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GuestDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Agent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
